# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: elliottmcclinton/hydro:latest

# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Tests not yet configured for master"
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - cp hydroponics/settings_secret.py.template hydroponics/settings_secret.py
          - echo -e "\n \n" >> hydroponics/settings_secret.py
          - echo "import os" >> hydroponics/settings_secret.py
          - echo "BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))" >> hydroponics/settings_secret.py
          - echo "DATABASES = {}" >> hydroponics/settings_secret.py
          - echo "DATABASES['default'] = {}" >> hydroponics/settings_secret.py
          - echo "DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'" >> hydroponics/settings_secret.py
          - echo "DATABASES['default']['NAME'] = os.path.join(BASE_DIR, 'db.sqlite3')" >> hydroponics/settings_secret.py
          - echo "ALLOWED_HOSTS = ['*']" >> hydroponics/settings_secret.py
          - echo "DEBUG = False" >> hydroponics/settings_secret.py
          - echo "LOGGING = False" >> hydroponics/settings_secret.py
          - printf 'yes\n' | python manage.py collectstatic
          - Xvfb :1 -screen 5 1024x768x8 &
          - export DISPLAY=:1.5
          - 'eval driver=chrome-headless REMOTE_USER=admin python manage.py test'
